#=============================================================
#                      Faction Engine
#=============================================================

# Enable or Disable faction guards spawn.
FactionEnableFactionGuards = True

# Enable or Disable map voting system. If disabled, map will be changed to the next on list.
FactionEnableMapVoting = False

# Enable or Disable faction members balance when player log in.
# Player will be moved to faction with less players.
FactionEnablePlayersBalanceLogin = True

# Team1 Faction Base location (x, y, z, min, max)
FactionTeam1Base = 45294,49941,-3068,50,50

# Team2 Faction Base location (x, y, z, min, max)
FactionTeam2Base = 45442,49932,-3068,50,50

# Team3 Faction Base location (x, y, z, min, max)
FactionTeam3Base = 147442,27312,-2201,50,50

# Spawn location for newbies (x, y, z, min, max)
FactionNewbieBase = 45346,49026,-3061,50,50


# Enable or Disable .online command to see online status of all factions
EnableOnlinePlayersVC = False
# Show online status of all factions on login
EnableOnlinePlayersEnterworld = False

# Enable or Disable anti pvp farm by IP protection
EnableProtectionIP = True	
# Enable or Disable anti pvp farm on same clan
EnableProtectionClan = False
# Enable or Disable anti pvp farm on same ally
EnableProtectionAlly = False
# Enable or Disable anti pvp farm by PDef protection (If target Pdef is less than "ProtectionArmourAmount" , player won't be rewarded)
EnableProtectionArmour = True
ProtectionArmourAmount = 300
# Enable or Disable protection for pvp rewards if player were killed two times in a row by same player.
EnableProtectionSamePlayer = False

# Enable or Disable support classes balance on factions.
# Players with support class won't be able to change their faction to another, where is more support classes
FactionEnableClassBalance = True

# Round time. After round end, players will receive voting html to vote for next map
# 120 = 2h. 60 = 1h. Default: 120 (In minutes)
MapTimeDuration = 15

# Teleport all players back to base on round end. Default: False
FactionEnableAutoTeleportToBase = True

# Price to chose new faction
PriceForFactionChange = 1000

# Faction Names
Team1Name = Furious
Team2Name = Fast

# Team Name Colors in RGB format.
Team1ColorName = 0000E0
Team2ColorName = F4FA58


# Custom levels at start and for subclass.
StartingLevel = 76
StartingLevelSubClass = 76

# Pvp kills needed to access special gmshop (id: 90) and equip S grade items
FactionKillsForSpecShop = 300
# Enable/Disable check for pvp kills when equiping S Grade item.
FactionForbidUseItem = True

# Enable or Disable A grade equipment limit.
FactionEnableAGradeLimit = True
# Kills needed to equip A Grade
FactionKillsForAGradeItem = 100

# Enable or Disable anti-heavy system.
# Dagger, tyrant, and bow classes won't be able to equip heavy type armours.
FactionEnableAntiHeavySystem = True

#-----------------------------------------------------------------------
#                          Npc/Player speak
#-----------------------------------------------------------------------
# Use %n for player name.
# Enable/Disable npc/player say text when chosing faction. "This is sparta!" and so on. Default: True
FactionEnableSayTexts = True

# Texts for team1 player and npc.
Team1NpcText = Thanks for Register in Furoius Team %n!
Team1PlayerText = I feel the power !!!

# Texts for team2 player and npc.
Team2NpcText = Thanks for Register in Fast Team %n!
Team2PlayerText = I feel the dark power !!

# Texts for team3 player and npc.
Team3NpcText = Licence and registry!
Team3PlayerText = I feel the dark power !!

#-----------------------------------------------------------------------
#                          Enchant system
#-----------------------------------------------------------------------
# Enchant system settings
# Types:
# PVPENCHANT (will be auto enchanted)
# PVPSCROLLS (players will get scrolls from pvp)
# OFF (simple enchant system).
# Commands - .setenchant and .info
FactionEnchantSystemType = PVPSCROLLS

# Drop chance for enchant scrolls in pvp. Default: 5%
# Type must be PVPSCROLLS.
# Player can get normal or blessed scrolls. Random.
FactionEnchantScrollsDropChance = 34

# TYPE must be PVPENCHANT
# Enchant limit for items.
MaxItemEnchant = 12
# Kills needed to auto enchant grade B item
KillsForEnchantB = 25
# Kills needed to auto enchant grade A item
KillsForEnchantA = 20
# Kills needed to auto enchant grade S item
KillsForEnchantS = 40

#-----------------------------------------------------------------------
#                     Sp, Item rewards for flags
#-----------------------------------------------------------------------
# Enable or Disable skill points and item reward by capturing enemy flag
FactionPlayerGetSpItemFlag = True

# Skill points amount, which player will receive by capturing enemy flag (first - clan level 1-5)(second - clan level 5-7)(third - clan level 7-8)(no clan - third)
FactionEngineAmmountSpFirstFlag = 157865
FactionEngineAmmountSpSecondFlag = 100875
FactionEngineAmmountSpThirdFlag = 75405

# Item reward, which player will receive by capturing enemy flag
# (first - clan level 1-5)(second - clan level 5-7)(third - clan level 7-8)(no clan = third)
# item_id,amount;item_id,amount...
FactionFlagReward1 = 57,6
FactionFlagReward2 = 57,3
FactionFlagReward3 = 57,2

#-----------------------------------------------------------------------
#                        Exp, points, rewards during pvp
#-----------------------------------------------------------------------
# Enable or Disable experience gain in PVP
FactionPlayerGetExp = True
# Experience reward in PVP (first - lvl75-76)(second - lvl76-78)(third - lvl 78-80)
FactionExpRewardInPvpFirst = 1000000
FactionExpRewardInPvpSecond = 2800000
FactionExpRewardInPvpThird = 120000
# Faction points reward by capturing enemy base
FactionPointsRewardFlag = 2
# Faction points reward by killing enemy faction member
FactionPointsRewardPvp = 3
# Player lose faction points on death
# Amount of points, which player will lose
PlayerLosePointsOnDeath = True
FactionPointsLoseAmount = 1

# Enable or Disable Item Rewards in Pvp
FactionPlayerGetItemByPvP = True
# Item Amount (Player will receive - (FactionEngineAmmountItemRewardPvp * Faction Flags Number))
FactionEngineAmmountItemRewardPvp = 2
# Item ID, which player will receive in PVP
FactionPvPItemRewardID = 57

#-----------------------------------------------------------------------
#                         Party related rewards
#-----------------------------------------------------------------------

# Enable or Disable Item Rewards in Pvp for Party members (also by capturing flags)
# Party rewards in pvp and by capturing flag is same as killer rewards.
FactionPlayerGetItemByPvPInParty = True

# Party Reward only for support classes
PartyRewardOnlySupportClass = False

# Reward item Id. Count is same as player pvp reward.
FactionRewardPvpItmId = 57

# Chance to get party reward. Default 100%
Chance = 50

# Killer reward if he got a party (Player reward + FactionPlayerRewardIfPp)
# If there is an box character of the killer, killer reward won't be increased.
FactionPlayerRewardIfPp = 2

#-----------------------------------------------------------------------
#                     Multiple rewards related to castles
#-----------------------------------------------------------------------

# Increase PVP rewards if clan owns the one of castles.
# PVP, Party related rewards must be enabled in order to work.
FactionEnableMultipleCastleReward = True

# Reward + value if player clan owns Aden castle.
FactionIncreaseRewardAden = 4

# Reward + value if player clan owns Dion castle.
FactionIncreaseRewardDion = 3

#Reward + value if player clan owns Gludio castle.
FactionIncreaseRewardGludio = 2

#-----------------------------------------------------------------------
#                         Round end rewards
#-----------------------------------------------------------------------
# SP reward for best player of the round
FactionEngineAmmountSpForFirstPlace = 200000
# Adena reward for best player of the round
FactionEngineAmmountAdenaFirstPlace = 60
# Ancient Adena reward for best player of the round. Can be enabled or disabled.
FactionEnableAaRewardFirstPlace = True
FactionEngineAmmountAaFirstPlace = 3
# Adena reward for second best player of the round
FactionEngineAmmountAdenaSecondPlace = 25
# Adena reward for third best player of the round
FactionEngineAmmountAdenaThirdPlace = 10
# Enable or Disable other item reward for best player (only for the best)
EnableItemRewardForTopPlayer = True
# Item id for reward
FactionItemRewardTopId = 5575
# Item amount for reward
FactionItemRewardTopAmount = 8

# Enable or Disable item reward for all players of winning faction
EnableRewardWinFaction = True
# Reward item id. 57 = Adena
FactionRewardWinFactionId = 5575
# Reward Amount
FactionRewardWinFactionAmount = 5

#-----------------------------------------------------------------------
#                         CLASS Balance
#-----------------------------------------------------------------------

# Magic critical attacks will be: (m.crit rate / ClassBalanceMcrit)
ClassBalanceMcrit = 1

# MATK = matk * ClassBalanceMAtk
ClassBalanceMAtk = 0.8

#-----------------------------------------------------------------------
#                         Chaos Event
#-----------------------------------------------------------------------

# Enable or disable Chaos event
EnableChaosEvent = False

# Super Haste skill level, which player will get. Max: 4
SuperHasteLvl = 2

# Chaos event duration time (Default: 20 minutes)
ChaosEventDuration = 1

# Chaos event interval (Default: 120 minutes)
ChaosEventInterval = 360

# Reward item id and amount for best player by pvp kills in chaos event
ChaosEventRewardId = 57
ChaosEventRewardAmount = 99
# Enable Aura Team
FactionAuraTeamEnable = True


