CREATE TABLE IF NOT EXISTS `mods_faction` (
  `char_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `factionId` INT UNSIGNED NOT NULL DEFAULT 0,
  `factionPoints` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`char_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
